
<?php if(!$block->isEmailExists() && $block->isEnabled()) :?>
<div id="popup-modal">
    <h3> How would you rate your Shopping Experience? </h3>
    <div class="messages" ><div class="message-error error message" data-message></div></div>
     <ul class = "hatslogic-smileys">
        <input id="rating" type="hidden" name="rating" value="">
        <li data-rating="cool"><img  alt="Cool" title ="Cool" src="<?php echo $block->getViewFileUrl('Hatslogic_ExperienceSurvey::images/icons/cool.png'); ?>" /></i></li>
        <li data-rating="good"><img  alt="Good" title ="Good" src="<?php echo $block->getViewFileUrl('Hatslogic_ExperienceSurvey::images/icons/good.png'); ?>" /></li>
        <li data-rating="ok"><img  alt="Ok" title ="Ok" src="<?php echo $block->getViewFileUrl('Hatslogic_ExperienceSurvey::images/icons/ok.png'); ?>" /></li>
        <li data-rating="angry"><img  alt="Angry" title ="Angry" src="<?php echo $block->getViewFileUrl('Hatslogic_ExperienceSurvey::images/icons/angry.png'); ?>" /></li>
     </ul>
     <h3>Do you have any comments to improve your experience ?</h3>
     <textarea class="form-control" row="8" id="comment"> </textarea>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'Magento_Customer/js/customer-data'
        ],
        function(
            $,
            modal,
            customerData
        ) {
            
            $('.hatslogic-smileys li').on("click",function(){
                
                $("#rating").val($(this).attr("data-rating"));
                $(this).siblings().removeClass("active");
                $(this).addClass('active');
            })
            
            $('.messages').hide();
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass : "hatslogic-order-rating",
                title: 'Rate your experience',
                buttons: [{
                    text: $.mage.__('Rate'),
                    class: '',
                    click: function () {
                        $.ajax({
                            url:"<?php echo $block->getAjaxUrl() ?>",
                            type:'POST',
                            showLoader: true,
                            dataType:'json',
                            data: {'email' : "<?php echo $block->getLastOrderCustomerEmail() ?>", 'rating' : $("#rating").val() , "comment" : $("#comment").val() },
                            complete: function(data) {
                                customerData.reload('messages');
                               
                                var response = data.responseJSON;
                                if(response.status != "ok"){
                                    $('[data-message]').text(response.message);
                                    $('.messages').show();
                                }else{
                                    
                                    customerData.set('messages', {
                                        messages: [{
                                            type: 'success',
                                            text: response.message
                                        }]
                                    });
                                    $("#popup-modal").modal(options).modal('closeModal');
                                }
                            },
                            error: function (xhr, status, errorThrown) {
                                
                                $('[data-message]').text("Internal Error !!! Try after sometime.");
                                $('.messages').show();
                            }
                        });

                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            setTimeout(function () {
                $('#popup-modal').modal('openModal');
            }, 1000);
            
        }
    );
</script>
<?php endif;?>